GET http://localhost:8081/api/weaponTypes
###

GET http://localhost:8081/api/weaponTypes/Katana

###

GET http://localhost:8081/api/weaponTypes/Long%20Sword

###

POST http://localhost:8081/api/weaponTypes
Content-Type: application/json

{
  "name": "LongSword",
  "attackType": "Slash",
  "inventionYear": "1985"
}

###

POST http://localhost:8081/api/weaponTypes
Content-Type: application/json

{
  "name": "Katana",
  "attackType": "Slash",
  "inventionYear": "1985"
}

###
GET http://localhost:8081/api/weaponTypes/Long%20Sword

###

PUT http://localhost:8081/api/weaponTypes/Long%20Sword
Content-Type: application/json

{
  "attackType": "Thrust",
  "inventionYear": "1985"
}

###
PUT http://localhost:8081/api/weaponTypes/Spade
Content-Type: application/json

{
  "attackType": "Thrust",
  "inventionYear": "1985"
}

###

###
DELETE http://localhost:8081/api/weaponTypes/Spade
###
DELETE http://localhost:8081/api/weaponTypes/Long%20Sword
###
DELETE http://localhost:8081/api/weaponTypes/Katana