
GET http://localhost:8080/api/weaponTypes/Katana/weapons

###

GET http://localhost:8080/api/weaponTypes/Katana/weapons/Zangetsu

###
GET http://localhost:8080/api/weapons

###

POST http://localhost:8080/api/weaponTypes/Zweihander/weapons
Content-Type: application/json

{
  "name": "Flamberge",

  "price": "123.1",

  "weight": "1213.1",

  "length": "23.1",

  "material": "Steel"

}

###

GET http://localhost:8080/api/weaponTypes/Zweihander/weapons/Flamberge

###

PUT http://localhost:8080/api/weaponTypes/Zweihander/weapons/Flamberge
Content-Type: application/json

{

  "price": "17.1",

  "weight": "28.1",

  "length": "12.1",

  "material": "Brass"

}

###
DELETE http://localhost:8080/api/weaponTypes/Zweihander/weapons/Flamberge

###

GET http://localhost:8080/api/weaponTypes
###

GET http://localhost:8080/api/weaponTypes/Katana

###

GET http://localhost:8080/api/weaponTypes/LongSword

###

POST http://localhost:8080/api/weaponTypes
Content-Type: application/json

{
  "name": "LongSword",
  "attackType": "Slash",
  "inventionYear": "1985"
}

###

POST http://localhost:8080/api/weaponTypes
Content-Type: application/json

{
  "name": "Katana",
  "attackType": "Slash",
  "inventionYear": "1985"
}

###
GET http://localhost:8080/api/weaponTypes/LongSword

###

PUT http://localhost:8080/api/weaponTypes/LongSword
Content-Type: application/json

{
  "attackType": "Thrust",
  "inventionYear": "1985"
}

###
PUT http://localhost:8080/api/weaponTypes/Spade
Content-Type: application/json

{
  "attackType": "Thrust",
  "inventionYear": "1985"
}

###

###
DELETE http://localhost:8080/api/weaponTypes/Spade
###
DELETE http://localhost:8080/api/weaponTypes/LongSword